package data

// SampleStm32Gpdsc returns a sample gpdsc xml file, NOTE: the example file is heavily simplified for ease of use with testing
func SampleStm32Gpdsc() []byte {
	gpdsc := `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- ******************************************************************************
 * File Name   : stm32cubeTest.gpdsc
 * Date        : 14/11/2018 20:32:58
 * Description : Generator PDSC File generated by STM32CubeMX (DO NOT EDIT!)
 ****************************************************************************** -->

<package xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1.4" xs:noNamespaceSchemaLocation="PACK.xsd">
  <vendor>STMicroelectronics</vendor>
  <name>stm32cubeTest</name>
  <description>STM32CubeMX generated pack description</description>
  <url>/home/nathaniel/projects/stm32cubeTest</url>
  <releases>
    <release version="1.0.0">
     - Generated: 14/11/2018 20:32:58
    </release>
  </releases>
  <requirements>
    <languages>
      <language name="C" version="99"/>
      <language name="C++" version="11"/>
    </languages> 
  </requirements>
  <create>
    <project>
      <options>
        <stack size="0x400"/> 
        <heap size="0x200"/>
        <debugProbe name="ST-Link" protocol="swd"/>
      </options> 
    </project>
  </create>
  <generators>
    <generator id="STM32CubeMX">
      <description>STM32CubeMX GPDSC</description>
      <select Dname="STM32L432KCUx" Dvendor="STMicroelectronics:13"/>
      <project_files>
        <file category="header" name="Inc/stm32l4xx_it.h"/>
        <file category="header" name="Inc/stm32l4xx_hal_conf.h"/>
        <file category="header" name="Inc/main.h"/>
        <file category="source" name="Src/stm32l4xx_it.c"/>
        <file category="source" name="Src/stm32l4xx_hal_msp.c"/>
        <file category="source" name="Src/main.c"/>
      </project_files>
    </generator>
  </generators>
  <taxonomy>
    <description Cclass="Device" Cgroup="STM32Cube Framework" generator="STM32CubeMX">STM32Cube Framework</description>
  </taxonomy>
  <conditions>
    <condition id="ARM Toolchain">
      <description>ARM compiler for C and C++ Filter</description>
      <require Tcompiler="ARMCC"/>
    </condition>
    <condition id="GCC Toolchain">
      <description>GNU Tools for ARM Embedded Processors Filter</description>
      <require Tcompiler="GCC"/>
    </condition>
    <condition id="IAR Toolchain">
      <description>IAR compiler for C and C++ Filter</description>
      <require Tcompiler="IAR"/>
    </condition>
  </conditions>

  <components>
    <component Cclass="CMSIS" Cgroup="CORE" Cversion="4.0.0">
      <description>CMSIS-CORE for ARM</description>
      <files>
        <file category="header" name="Drivers\CMSIS\Include\core_cm4.h"/>
      </files>
    </component>
    <component Cclass="Device" Cgroup="Startup" Cversion="2.1.0">  
      <description>System Startup for STMicroelectronics</description>
      <files>
        <file category="header" name="Drivers\CMSIS\Device\ST\STM32L4xx\Include\stm32l4xx.h"/>
        <file category="sourceAsm" condition="IAR Toolchain" name="Drivers\CMSIS\Device\ST\STM32L4xx\Source\Templates\iar\startup_stm32l432xx.s"/>
        <file category="sourceAsm" condition="GCC Toolchain" name="Drivers\CMSIS\Device\ST\STM32L4xx\Source\Templates\gcc\startup_stm32l432xx.s"/>
      </files>
    </component>
    </components>
</package>
`
	return []byte(gpdsc)
}
