# CMSIS-CORE for ARM  CMSIS:CORE:, version:4.0.0
cc_library(
    name = "CMSIS_CORE_",
    srcs = ["Drivers/CMSIS/Include/core_cm4.h"],
    hdrs = ["Drivers/CMSIS/Include/core_cm4.h"],
    linkstatic = "True",
)

# System Startup for STMicroelectronics  Device:Startup:, version:2.1.0
cc_library(
    name = "Device_Startup_",
    srcs = [
        "Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4xx.h",
        "Drivers/CMSIS/Device/ST/STM32L4xx/Include/system_stm32l4xx.h",
        "Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/arm/startup_stm32l432xx.s",
        "Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/startup_stm32l432xx.s",
        "Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/iar/startup_stm32l432xx.s",
        "Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/system_stm32l4xx.c",
    ],
    hdrs = [
        "Drivers/CMSIS/Device/ST/STM32L4xx/Include/stm32l4xx.h",
        "Drivers/CMSIS/Device/ST/STM32L4xx/Include/system_stm32l4xx.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:COMMON, version:1.3.2
cc_library(
    name = "Device_STM32CubeHAL_COMMON",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c",
    ],
    hdrs = ["Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h"],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:RCC, version:0.8.4
cc_library(
    name = "Device_STM32CubeHAL_RCC",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_rcc.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_rcc_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_rcc.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_rcc_ex.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:CORTEX, version:0.8.4
cc_library(
    name = "Device_STM32CubeHAL_CORTEX",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_cortex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c",
    ],
    hdrs = ["Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_cortex.h"],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:TIM, version:1.0.0
cc_library(
    name = "Device_STM32CubeHAL_TIM",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_tim.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_tim_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_tim.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_tim_ex.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:UART, version:0.3.0
cc_library(
    name = "Device_STM32CubeHAL_UART",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_uart.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_uart_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_uart.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_uart_ex.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:COMMON, version:0.3.0
cc_library(
    name = "Device_STM32CubeHAL_COMMON",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_def.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_i2c.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_i2c_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_def.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_i2c.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_i2c_ex.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:DMA, version:0.8.4
cc_library(
    name = "Device_STM32CubeHAL_DMA",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_dma.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_dma_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_dma.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_dma_ex.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:PWR, version:0.8.4
cc_library(
    name = "Device_STM32CubeHAL_PWR",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_pwr.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_pwr_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_pwr.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_pwr_ex.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:FLASH, version:0.8.4
cc_library(
    name = "Device_STM32CubeHAL_FLASH",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash_ramfunc.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash_ramfunc.h",
    ],
    linkstatic = "True",
)

# CubeMX Generated HAL COMMON  Device:STM32Cube HAL:GPIO, version:0.8.4
cc_library(
    name = "Device_STM32CubeHAL_GPIO",
    srcs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_gpio.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_gpio_ex.h",
        "Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c",
    ],
    hdrs = [
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_gpio.h",
        "Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_gpio_ex.h",
    ],
    linkstatic = "True",
)

# stm32cubeTest, Device:STM32L432KCUx
cc_binary(
    name = "stm32cubeTest_STM32L432KCUx",
    srcs = [
        "Inc/main.h",
        "Inc/stm32l4xx_hal_conf.h",
        "Inc/stm32l4xx_it.h",
        "Src/main.c",
        "Src/stm32l4xx_hal_msp.c",
        "Src/stm32l4xx_it.c",
    ],
    hdrs = [
        "Inc/main.h",
        "Inc/stm32l4xx_hal_conf.h",
        "Inc/stm32l4xx_it.h",
    ],
    deps = [
        ":CMSIS_CORE_",
        ":Device_STM32CubeHAL_COMMON",
        ":Device_STM32CubeHAL_CORTEX",
        ":Device_STM32CubeHAL_DMA",
        ":Device_STM32CubeHAL_FLASH",
        ":Device_STM32CubeHAL_GPIO",
        ":Device_STM32CubeHAL_PWR",
        ":Device_STM32CubeHAL_RCC",
        ":Device_STM32CubeHAL_TIM",
        ":Device_STM32CubeHAL_UART",
        ":Device_Startup_",
    ],
)
